import React, { useState, useRef, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { ChevronLeft, LoaderCircle, X } from "lucide-react";
import { ErrorDrawer } from "@/components/ui/ErrorDrawer";
import { SuccessDrawer } from "@/components/ui/SuccessDrawer";
import { totpService } from "@/services/totp";
import { useAuth } from "@/contexts/AuthContext";

interface OTPPageProps {
  title?: string;
  description?: string;
  onVerify?: (
    otp: string
  ) => Promise<{ success: boolean; message?: string; error?: string }>;
  onSuccess?: () => void;
}

export const OTPPage: React.FC<OTPPageProps> = ({
  title = "Authenticator App Verification",
  description = "Enter the 6-digit code generated by the Authenticator App.",
  onVerify,
  onSuccess,
}) => {
  const navigate = useNavigate();
  const { refreshUser } = useAuth();
  const inputRef = useRef<HTMLInputElement>(null);

  const [code, setCode] = useState("");
  const [isVerifying, setIsVerifying] = useState(false);
  const [error, setError] = useState(false);
  const [errorDrawer, setErrorDrawer] = useState({
    isOpen: false,
    title: "",
    message: "",
  });
  const [successDrawer, setSuccessDrawer] = useState({
    isOpen: false,
    title: "",
    message: "",
  });

  const handleBackClick = () => {
    navigate(-1);
  };

  const handlePaste = async () => {
    try {
      const text = await navigator.clipboard.readText();
      const sanitized = text.replace(/[^0-9]/g, "").slice(0, 6);
      setCode(sanitized);
      setError(false);
      if (inputRef.current) {
        inputRef.current.focus();
      }

      if (sanitized.length === 6) {
        setTimeout(() => {
          handleSubmit(sanitized);
        }, 100);
      }
    } catch (err) {
      console.error("Failed to paste:", err);
    }
  };

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value.replace(/[^0-9]/g, "").slice(0, 6);
    setCode(value);
    setError(false);
  };

  useEffect(() => {
    if (code.length === 6 && !isVerifying) {
      handleSubmit(code);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [code]);

  const handleSubmit = async (codeToVerify?: string) => {
    const verificationCode = codeToVerify || code;
    if (verificationCode.length !== 6 || isVerifying) return;

    setIsVerifying(true);
    setError(false);

    try {
      const response = onVerify
        ? await onVerify(verificationCode)
        : await totpService.verify({ token: verificationCode });

      if (response.success) {
        setSuccessDrawer({
          isOpen: true,
          title: "Verification Successful!",
          message:
            response.message ||
            "Your authenticator has been verified successfully.",
        });

        // Refetch user data
        await refreshUser();

        setTimeout(() => {
          if (onSuccess) {
            onSuccess();
          } else {
            navigate("/profile", { replace: true });
          }
        }, 2000);
      } else {
        setError(true);
        setErrorDrawer({
          isOpen: true,
          title: "Verification Failed",
          message:
            response.error ||
            response.message ||
            "The code you entered is incorrect. Please try again.",
        });
        setCode("");
      }
    } catch (err: any) {
      setError(true);
      setErrorDrawer({
        isOpen: true,
        title: "Something went wrong",
        message:
          err.message ||
          "An error occurred during verification. Please try again.",
      });
      setCode("");
    } finally {
      setIsVerifying(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#181818] flex flex-col">
      {/* Header */}
      <div className="flex items-center justify-between px-6 py-8">
        <button
          onClick={handleBackClick}
          className="w-8 h-8 flex items-center justify-center"
        >
          <ChevronLeft color="#C7EF6B" size={24} />
        </button>
      </div>

      {/* Content */}
      <div className="flex-1 px-6 pb-8">
        <div className="w-full">
          {/* Title */}
          <h1 className="text-xl font-semibold text-white/90">{title}</h1>

          {/* Description */}
          <p className="text-gray-400 text-sm mb-6">{description}</p>

          {/* Input Section */}
          <div className="space-y-3 mb-6">
            <label className="text-gray-400 text-sm ">Authenticator App</label>
            <div className="relative mt-1">
              <input
                ref={inputRef}
                type="text"
                inputMode="numeric"
                maxLength={6}
                value={code}
                onChange={handleInputChange}
                placeholder=""
                disabled={isVerifying}
                className={`w-full px-4 py-3 pr-20 rounded-lg text-white text-lg bg-[#1a1a1a] border transition-colors ${
                  error
                    ? "border-red-500 focus:border-red-500"
                    : "border-[#2a2a2a] focus:border-[#C7EF6B]"
                } focus:outline-none disabled:opacity-50 disabled:cursor-not-allowed`}
              />
              <button
                onClick={handlePaste}
                disabled={isVerifying}
                className="absolute right-4 top-1/2 -translate-y-1/2 text-[#C7EF6B] text-sm font-medium hover:text-[#B8E55A] disabled:opacity-50 disabled:cursor-not-allowed"
              >
                Paste
              </button>
            </div>
          </div>

          {/* Submit Button */}
          <button
            onClick={() => handleSubmit()}
            disabled={code.length !== 6 || isVerifying}
            className={`w-full py-3 rounded-xl font-semibold text-lg transition-colors ${
              code.length === 6 && !isVerifying
                ? "bg-[#C7EF6B] text-black hover:bg-[#B8E55A]"
                : "bg-[#636363] text-white cursor-not-allowed"
            }`}
          >
            {isVerifying ? (
              <span className="flex items-center justify-center gap-2">
                <LoaderCircle className="animate-spin h-5 w-5 text-white" />
                Verifying...
              </span>
            ) : (
              "Submit"
            )}
          </button>

          {/* Action Links */}
          {/* <div className="space-y-4 pt-4">
            <button
              onClick={() => navigate("/setup-otp")}
              className="text-[#C7EF6B] text-sm font-medium hover:underline"
            >
              No authenticator app? Setup a new one.
            </button>
          </div> */}
        </div>
      </div>

      {/* Error Drawer */}
      <ErrorDrawer
        isOpen={errorDrawer.isOpen}
        onClose={() => {
          setErrorDrawer({ isOpen: false, title: "", message: "" });
          setError(false);
        }}
        title={errorDrawer.title}
        message={errorDrawer.message}
      />

      {/* Success Drawer */}
      <SuccessDrawer
        isOpen={successDrawer.isOpen}
        onClose={() =>
          setSuccessDrawer({ isOpen: false, title: "", message: "" })
        }
        title={successDrawer.title}
        message={successDrawer.message}
      />
    </div>
  );
};
