/**
 * OTP Verification Drawer
 * Drawer component for verifying OTP codes from authenticator apps
 */

import React, { useState, useRef, useEffect } from "react";
import { X, LoaderCircle } from "lucide-react";
import {
  Drawer,
  DrawerContent,
  DrawerHeader,
  DrawerTitle,
  DrawerFooter,
} from "@/components/ui/drawer";
import { ErrorDrawer } from "@/components/ui/ErrorDrawer";
import { SuccessDrawer } from "@/components/ui/SuccessDrawer";
import { totpService } from "@/services/totp";
import { TOTPSetupDrawer } from "./TOTPSetupDrawer";

interface OTPVerificationDrawerProps {
  isOpen: boolean;
  onClose: () => void;
  title?: string;
  description?: string;
  onVerify?: (
    otp: string
  ) => Promise<{ success: boolean; message?: string; error?: string }>;
  onSuccess?: () => void;
  showSuccessDrawer?: boolean;
}

export const OTPVerificationDrawer: React.FC<OTPVerificationDrawerProps> = ({
  isOpen,
  onClose,
  title = "Authenticator App Verification",
  description = "Enter the 6-digit code generated by the Authenticator App.",
  onVerify,
  onSuccess,
  showSuccessDrawer = false,
}) => {
  const inputRef = useRef<HTMLInputElement>(null);

  const [code, setCode] = useState("");
  const [isVerifying, setIsVerifying] = useState(false);
  const [error, setError] = useState(false);
  const [hasVerified, setHasVerified] = useState(false);
  const [showSetupDrawer, setShowSetupDrawer] = useState(false);
  const [errorDrawer, setErrorDrawer] = useState({
    isOpen: false,
    title: "",
    message: "",
  });
  const [successDrawer, setSuccessDrawer] = useState({
    isOpen: false,
    title: "",
    message: "",
  });

  const handleSetupComplete = () => {
    setShowSetupDrawer(false);
  };

  // Reset state when drawer opens/closes
  useEffect(() => {
    if (isOpen) {
      setCode("");
      setError(false);
      setIsVerifying(false);
      setHasVerified(false);

      setTimeout(() => {
        if (inputRef.current) {
          inputRef.current.focus();
        }
      }, 100);
    }
  }, [isOpen]);

  const handlePaste = async () => {
    try {
      const text = await navigator.clipboard.readText();
      const sanitized = text.replace(/[^0-9]/g, "").slice(0, 6);
      setCode(sanitized);
      setError(false);
      if (inputRef.current) {
        inputRef.current.focus();
      }

      // Auto-submit if 6 digits
      if (sanitized.length === 6) {
        // Small delay to show the pasted code
        setTimeout(() => {
          handleSubmit(sanitized);
        }, 100);
      }
    } catch (err) {
      console.error("Failed to paste:", err);
    }
  };

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value.replace(/[^0-9]/g, "").slice(0, 6);
    setCode(value);
    setError(false);
  };

  // Auto-submit when 6 digits are entered
  useEffect(() => {
    if (code.length === 6 && !isVerifying && !hasVerified && isOpen) {
      handleSubmit(code);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [code, isOpen, hasVerified]);

  const handleSubmit = async (codeToVerify?: string) => {
    const verificationCode = codeToVerify || code;
    if (verificationCode.length !== 6 || isVerifying || hasVerified) return;

    setIsVerifying(true);
    setError(false);

    try {
     
      const response = onVerify
        ? await onVerify(verificationCode)
        : await totpService.verify({ token: verificationCode });

      if (response.success) {
        setIsVerifying(false);
        setHasVerified(true); 
        setCode(""); 
        if (onSuccess) {
          onSuccess();
        }
        onClose();
      } else {
        setError(true);
        setErrorDrawer({
          isOpen: true,
          title: "Verification Failed",
          message:
            response.error ||
            response.message ||
            "The code you entered is incorrect. Please try again.",
        });
        setCode("");
      }
    } catch (err: any) {
      setError(true);
      setErrorDrawer({
        isOpen: true,
        title: "Something went wrong",
        message:
          err.message ||
          "An error occurred during verification. Please try again.",
      });
      setCode("");
    } finally {
      setIsVerifying(false);
    }
  };

  const handleSetupOTP = (
    e: React.MouseEvent<HTMLElement> | React.KeyboardEvent<HTMLElement>
  ) => {
    e.preventDefault();
    e.stopPropagation();
    if (e.nativeEvent) {
      e.nativeEvent.stopImmediatePropagation();
    }
    setShowSetupDrawer(true);
    return false;
  };

  return (
    <>
      <Drawer open={isOpen} onOpenChange={(open) => !open && onClose()}>
        <DrawerContent className="bg-[#1a1a1a] border-[#2a2a2a]">
          <DrawerHeader className="relative">
            <DrawerTitle className="text-xl font-semibold text-white/90 text-left">
              {title}
            </DrawerTitle>
            <p className="text-gray-400 text-sm text-left">{description}</p>
          </DrawerHeader>

          <div className="pb-2">
            {/* Input Section */}
            <div className="space-y-3 mt-4">
              <div className="relative mt-1">
                <input
                  ref={inputRef}
                  type="text"
                  inputMode="numeric"
                  maxLength={6}
                  value={code}
                  onChange={handleInputChange}
                  placeholder=""
                  disabled={isVerifying}
                  className={`w-full px-4 py-3 pr-20 rounded-lg text-white text-lg bg-[#1a1a1a] border transition-colors ${
                    error
                      ? "border-red-500 focus:border-red-500"
                      : "border-[#2a2a2a] focus:border-[#C7EF6B]"
                  } focus:outline-none disabled:opacity-50 disabled:cursor-not-allowed`}
                />
                <button
                  onClick={handlePaste}
                  disabled={isVerifying}
                  className="absolute right-4 top-1/2 -translate-y-1/2 text-[#C7EF6B] text-sm font-medium hover:text-[#B8E55A] disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  Paste
                </button>
              </div>
            </div>
            <div className="text-start mt-2">
              <div
                role="button"
                tabIndex={0}
                onClick={handleSetupOTP}
                onKeyDown={(e) => {
                  if (e.key === "Enter" || e.key === " ") {
                    e.preventDefault();
                    handleSetupOTP(e as any);
                  }
                }}
                className="text-[#C7EF6B] text-xs font-medium hover:underline cursor-pointer"
              >
                No authenticator app? Setup a new one.
              </div>
            </div>
          </div>

          <DrawerFooter>
            <button
              onClick={() => handleSubmit()}
              disabled={code.length !== 6 || isVerifying}
              className={`w-full py-3 rounded-xl font-semibold text-lg transition-colors ${
                code.length === 6 && !isVerifying
                  ? "bg-[#C7EF6B] text-black hover:bg-[#B8E55A]"
                  : "bg-[#636363] text-white cursor-not-allowed"
              }`}
            >
              {isVerifying ? (
                <span className="flex items-center justify-center gap-2">
                  <LoaderCircle className="animate-spin h-5 w-5 text-white" />
                  Verifying...
                </span>
              ) : (
                "Submit"
              )}
            </button>
          </DrawerFooter>
        </DrawerContent>
      </Drawer>

      {/* TOTP Setup Drawer */}
      <TOTPSetupDrawer
        isOpen={showSetupDrawer}
        onClose={() => setShowSetupDrawer(false)}
        onComplete={handleSetupComplete}
        preserveState={{ keepExportDrawerOpen: true }}
      />

      {/* Error Drawer */}
      <ErrorDrawer
        isOpen={errorDrawer.isOpen}
        onClose={() => {
          setErrorDrawer({ isOpen: false, title: "", message: "" });
          setError(false);
        }}
        title={errorDrawer.title}
        message={errorDrawer.message}
      />

      {/* Success Drawer */}
      <SuccessDrawer
        isOpen={successDrawer.isOpen}
        onClose={() =>
          setSuccessDrawer({ isOpen: false, title: "", message: "" })
        }
        title={successDrawer.title}
        message={successDrawer.message}
      />
    </>
  );
};
